require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '254742063632',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0NVT3NZaXFrWXdpWjRLQ2VFdkZSOWRzS2tTOTdBa3I3a29VUkFqd0JVND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaU9UWllkem9SaC9hTFZDaDkwZUFNZ0JHTVlEd2RLSHh4d3BhRVkzNkNUVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLUGZzeVhqN1liTmw4ZlE1WktjSkJEV0pVNzlHdCtkTmRhREIxdGlrTzI4PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ0RmVMN0djUFpzRUxjY2xwMGNoOStzWGg5RVA5VkpVSkQ0K1UzdSs1bkFVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNJMk53V1Y1dUxKTlNobHU5eGd2N2FJSUcwN2VsSjA1NG1aWE9tN2ZJbEk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjR5ZDdUS0J6WlYzbkZRRVdxTWFmc3BLMWhpUVhHdXRYVGxWZE5pamVQQXM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWVBiOFdTM1dDSFdpYzk4MlJUUS9YM3NZRlYxVUd1TzVZNjdmN3lNblVtRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRDFuV0I0STlNa0I4Vjc5YU8wZ1NvL1crZktlYWFPWkdRTTZSNjVSaUVYWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdkdkJBeXVjdmt4MnY5TjNXWXNCYWsyc2pqTXY5aHRETGNzTEUrUWN5MzFJdTBrMEE2cXFlWVlERkY2K2lPay83Rk1WNFRkUjhzL21SbjBJOGRVZGlRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NiwiYWR2U2VjcmV0S2V5IjoialBhRG5jVXE0MXhCbHZkaXZlN2pUWjdEMjZHVVV4bVRLeWlWTlBhRFlXUT0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOlt7ImtleSI6eyJyZW1vdGVKaWQiOiI5MTc2NzkxMTY5MjJAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUNDMDM2ODY4RTYxMzE1N0I1MUFCQjEzNzJBM0FGNzkifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1ODM4MTE3MX0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTE3Njc5MTE2OTIyQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDOTIwNzA2NzAwQjkwNjgxQUQ3N0UzRTA4RTEyNDFGIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTgzODExNzF9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkxNzY3OTExNjkyMkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQzQ2NUJCNkE1NTVGMEVGRkMzNjUwQzkwQjY5NUUxRCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU4MzgxMTkwfV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiI3WDFOOVg5OSIsIm1lIjp7ImlkIjoiOTE3Njc5MTE2OTIyOjE5QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMjAzNjU0NTY0OTg2OTI2OjE5QGxpZCIsIm5hbWUiOiLinaTqp4Hhg6biirEgTW91bWl0YSBQcmFoYXJhaiDhg6bqp4LinaQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0tqdWhhMERFT0NJdThZR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImRDN2xKOXY4L0lDRDNsYSt4dWpVY3lacU1kWFNEclpiWkdIaHBoOEI3Mmc9IiwiYWNjb3VudFNpZ25hdHVyZSI6IlIzZnZOUGw0Z29iUDVMT05pZ3I2dzBDT05RVGVCSDUzQklVck9kQUxTaDJDYzg0eFRrUC9rQ29TZXJ6aEgyZXhieS8rN25xUjNiRmNOeWtYWlNpZURnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJ1SlhRMDI1ZmxGekpoL0RQdlo0L1dZQVhHN0ozTHU3allxdnJBTmVpN09FMDFZZjkzMkNBTE41MkRneXhTQS9iL1BiZmtNdGUwaUNKTXhiNmxYUzVodz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkxNzY3OTExNjkyMjoxOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJYUXU1U2ZiL1B5QWc5NVd2c2JvMUhNbWFqSFYwZzYyVzJSaDRhWWZBZTlvIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQVVJQWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTgzODExNjYsImxhc3RQcm9wSGFzaCI6IkM0ZkpOIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFJQksifQ==',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, || '203654564986926'

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
